export const registry = [
  {
    id: "6FcJaAzQnuoA6o3sVw1GD6Ba69XuL5jinZpQTzJhd2R3",
    key: "HNYG",
    name: "Honey Genesis Bees",
    verifiedCreator: "6vRx1iVZo3xfrBHdpvuwArL2jucVj9j9nLpd2VUTTGMG",
    nftOracle: "Gh5qsBcu69YbZcELwo5MGhVcpL5RUYDKPnn3wPngdEew",
    collectionUrl: "https://magiceden.io/marketplace/honey_genesis_bee",
    imgPath: "imgs/honey_genesis_bee.png",
    rate: 0,
    available: 0,
    value: 0,
    allowance: 0,
    positions: [],
    connection: null,
    user: null,
    debt: 0,
    utilizationRate: 0,
  },
  {
    id: "F8rZviSSuqgkTsjMeoyrTUSNSqh7yNDCAozJkxm7eujY",
    key: "BURR",
    name: "Burrito Boyz",
    verifiedCreator: "LoVExNPPxkeNnyLL8CT4Tuoc69JjTkfpsqcPsragvR4",
    nftOracle: "ZX5uhqNmGX3rcHsQ37n4LhN1yEraS1FZYudQocwD9LX",
    collectionUrl: "https://magiceden.io/marketplace/burrito_boyz",
    imgPath: "imgs/burrito_boyz.webp",
    rate: 0,
    available: 0,
    value: 0,
    allowance: 0,
    positions: [],
    connection: null,
    user: null,
    debt: 0,
    utilizationRate: 0,
  },
  {
    id: "Bxk1JQCbVjpeFnjzvH5n9bepnZeHjRADUFwZiVC7L5Gq",
    key: "ATD",
    name: "OG Atadians",
    verifiedCreator: "4pi2MRDQgGVFwV1Hv8ka7hSSu9TgdFmafk6jtQhrB9HN",
    nftOracle: "pPHUCjfN6dShY2Jf3SEvE5Uq59YRp6HdoY9CgVofZQm",
    collectionUrl: "https://magiceden.io/marketplace/atadians",
    imgPath: "imgs/atadians.gif",
    rate: 0,
    available: 0,
    value: 0,
    allowance: 0,
    positions: [],
    connection: null,
    user: null,
    debt: 0,
    utilizationRate: 0,
  },
  {
    id: "H2H2pJuccdvpET9A75ajB3GgdYdCUL4T3kiwUMA6DJ7q",
    key: "LIFINITY",
    name: "Lifinity Flares",
    verifiedCreator: "EWyWxSkxWHWGzxfCd9kG7zGrKTUDbZGiV6VbFJF8YfqN",
    nftOracle: "3Rgzsb37bDznYHSn1zsahaVrdbeBStEkXb26SokkVuzf",
    collectionUrl: "https://magiceden.io/marketplace/lifinity_flares",
    imgPath: "imgs/lifinity.png",
    rate: 0,
    available: 0,
    value: 0,
    allowance: 0,
    positions: [],
    connection: null,
    user: null,
    debt: 0,
    utilizationRate: 0,
  },
  {
    id: "GrKPvcdHVb4cwR5a2CCgCTvdkSqhNDRgSUiUVzXRWLk6",
    key: "BSL",
    name: "Smyths",
    verifiedCreator: "8m2b8ar9BNZErJQgSBwY3eCe73yR4k9qHUxxGffxyw2d",
    nftOracle: "ZX5uhqNmGX3rcHsQ37n4LhN1yEraS1FZYudQocwD9LX",
    collectionUrl: "https://magiceden.io/marketplace/blocksmith_labs",
    imgPath: "imgs/smyths.png",
    rate: 0,
    available: 0,
    value: 0,
    allowance: 0,
    positions: [],
    connection: null,
    user: null,
    debt: 0,
    utilizationRate: 0,
  },
];
